"""Add Vexa integration tables

Revision ID: b7db470ebeaf
Revises: d44358b8a236
Create Date: 2025-03-27 20:12:30.585374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7db470ebeaf'
down_revision: Union[str, None] = 'd44358b8a236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vexa_integration_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enable_recording', sa.Boolean(), nullable=True),
    sa.Column('enable_summary', sa.Boolean(), nullable=True),
    sa.Column('enable_search', sa.Boolean(), nullable=True),
    sa.Column('vexa_token', sa.String(length=255), nullable=True),
    sa.Column('browser_extension_installed', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_vexa_integration_settings_id'), 'vexa_integration_settings', ['id'], unique=False)
    op.create_table('vexa_meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vexa_meeting_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('connection_id', sa.String(length=100), nullable=False),
    sa.Column('meeting_metadata', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vexa_meetings_id'), 'vexa_meetings', ['id'], unique=False)
    op.create_index(op.f('ix_vexa_meetings_vexa_meeting_id'), 'vexa_meetings', ['vexa_meeting_id'], unique=True)
    op.create_table('vexa_audio_streams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.String(length=100), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('stream_status', sa.String(length=50), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('stream_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['vexa_meetings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vexa_audio_streams_connection_id'), 'vexa_audio_streams', ['connection_id'], unique=False)
    op.create_index(op.f('ix_vexa_audio_streams_id'), 'vexa_audio_streams', ['id'], unique=False)
    op.create_table('vexa_meeting_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('key_points', sa.Text(), nullable=True),
    sa.Column('action_items', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['vexa_meetings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id')
    )
    op.create_index(op.f('ix_vexa_meeting_summaries_id'), 'vexa_meeting_summaries', ['id'], unique=False)
    op.create_table('vexa_transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('vexa_transcript_id', sa.String(length=100), nullable=False),
    sa.Column('speaker', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['vexa_meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vexa_transcripts_id'), 'vexa_transcripts', ['id'], unique=False)
    op.drop_index('ix_voice_input_logs_id', table_name='voice_input_logs')
    op.drop_table('voice_input_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_input_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('audio_duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('audio_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recognition_success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('recognition_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('recognition_error', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], name='voice_input_logs_thread_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='voice_input_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='voice_input_logs_pkey')
    )
    op.create_index('ix_voice_input_logs_id', 'voice_input_logs', ['id'], unique=False)
    op.drop_index(op.f('ix_vexa_transcripts_id'), table_name='vexa_transcripts')
    op.drop_table('vexa_transcripts')
    op.drop_index(op.f('ix_vexa_meeting_summaries_id'), table_name='vexa_meeting_summaries')
    op.drop_table('vexa_meeting_summaries')
    op.drop_index(op.f('ix_vexa_audio_streams_id'), table_name='vexa_audio_streams')
    op.drop_index(op.f('ix_vexa_audio_streams_connection_id'), table_name='vexa_audio_streams')
    op.drop_table('vexa_audio_streams')
    op.drop_index(op.f('ix_vexa_meetings_vexa_meeting_id'), table_name='vexa_meetings')
    op.drop_index(op.f('ix_vexa_meetings_id'), table_name='vexa_meetings')
    op.drop_table('vexa_meetings')
    op.drop_index(op.f('ix_vexa_integration_settings_id'), table_name='vexa_integration_settings')
    op.drop_table('vexa_integration_settings')
    # ### end Alembic commands ###
