"""Add PromptLog model

Revision ID: c6b164aa9c89
Revises: 886cb47dbdb7
Create Date: 2025-03-03 15:15:09.768220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c6b164aa9c89'
down_revision: Union[str, None] = '886cb47dbdb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(length=50), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_logs_id'), 'prompt_logs', ['id'], unique=False)
    op.drop_column('documents', 'document_url')
    op.drop_column('documents', 'document_id')
    op.drop_column('documents', 'document_name')
    op.drop_column('documents', 'document_num')
    op.drop_column('documents', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('documents', sa.Column('document_num', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('documents', sa.Column('document_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('documents', sa.Column('document_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('document_url', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_prompt_logs_id'), table_name='prompt_logs')
    op.drop_table('prompt_logs')
    # ### end Alembic commands ###
